apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: default
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: apps
    repoURL: https://atc-github.azure.cloud.bmw/qxz59pp/argo-app-of-apps-test
    targetRevision: HEAD
  project: default

