apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    path: ./test-app
    repoURL: https://github.com/guimmn2/argocd-app-of-apps-test
    targetRevision: HEAD
